### ISSUE TITLE
Loading script does not work

### ISSUE THREAD

**Issue by stevenmeijer** [TH3steven/Context-TFP#48]
Trying to load a script from the main menu gives the following error: `java.lang.ClassNotFoundException: main.java.nl.tudelft.contextproject.presets.InstantPreset`

**Comment by bvobart** [comment]
@TH3steven That is because you're using an old savefile that still has the old class names in there. If you now save the script again, or if you cannot, remove every instance of `main.java.` from your savefile, then it will work again.

Let me know if this worked for you. If it did, then don't forget to close the issue ;)

**Comment by stevenmeijer** [comment]
@bvobart Check, that does work. I do however think this implementation could be done better, since as it appears here, these savefiles are not version independable and future versions of our code might break savefiles again.
